### ISSUE TITLE
crash on entry creation

### ISSUE THREAD

**Issue by ghost** [Gyro7/Osiris-pwm#4]
the app crashes when i create an entry, windows 10 version 1.0 of osirid

**Comment by liamtoaldo** [comment]
gonna work on that tomorrow 👍, also willing to implement patch 1.1 on windows too

**Comment by liamtoaldo** [comment]
> the app crashes when i create an entry, windows 10 version 1.0 of osirid

sorry for the late response, but I'm finally working on it!
Also I added a searchbar in the new version (1.1)

**Comment by ghost** [comment]
no problem! i also Lost Osirid cuz my dumbass brother runned Valravn lmao

Il sab 20 feb 2021, 17:59 Gyro7 <notifications@github.com> ha scritto:

**Comment by liamtoaldo** [comment]
Fixed it, check the new release! (1.1) https://github.com/Gyro7/Osiris-pwm/releases/tag/Osiris-v1.1-windows
Also btw, can you check if it works for me?
